// Generated by the protocol buffer compiler.  DO NOT EDIT!

package bg.smoc.model;

public final class GradeProto {
  private GradeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Grade extends
      com.google.protobuf.GeneratedMessage {
    // Use Grade.newBuilder() to construct.
    private Grade() {}
    
    private static final Grade defaultInstance = new Grade();
    public static Grade getDefaultInstance() {
      return defaultInstance;
    }
    
    public Grade getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bg.smoc.model.GradeProto.internal_static_model_Grade_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bg.smoc.model.GradeProto.internal_static_model_Grade_fieldAccessorTable;
    }
    
    // required string taskName = 1;
    public static final int TASKNAME_FIELD_NUMBER = 1;
    private boolean hasTaskName;
    private java.lang.String taskName_ = "";
    public boolean hasTaskName() { return hasTaskName; }
    public java.lang.String getTaskName() { return taskName_; }
    
    // required string language = 2;
    public static final int LANGUAGE_FIELD_NUMBER = 2;
    private boolean hasLanguage;
    private java.lang.String language_ = "";
    public boolean hasLanguage() { return hasLanguage; }
    public java.lang.String getLanguage() { return language_; }
    
    // repeated int32 testIndexes = 3;
    public static final int TESTINDEXES_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> testIndexes_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Integer> getTestIndexesList() {
      return testIndexes_;
    }
    public int getTestIndexesCount() { return testIndexes_.size(); }
    public int getTestIndexes(int index) {
      return testIndexes_.get(index);
    }
    
    // repeated string maxPoints = 4;
    public static final int MAXPOINTS_FIELD_NUMBER = 4;
    private java.util.List<java.lang.String> maxPoints_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getMaxPointsList() {
      return maxPoints_;
    }
    public int getMaxPointsCount() { return maxPoints_.size(); }
    public java.lang.String getMaxPoints(int index) {
      return maxPoints_.get(index);
    }
    
    // required bool explicitGrade = 5;
    public static final int EXPLICITGRADE_FIELD_NUMBER = 5;
    private boolean hasExplicitGrade;
    private boolean explicitGrade_ = false;
    public boolean hasExplicitGrade() { return hasExplicitGrade; }
    public boolean getExplicitGrade() { return explicitGrade_; }
    
    // required int32 taskType = 16;
    public static final int TASKTYPE_FIELD_NUMBER = 16;
    private boolean hasTaskType;
    private int taskType_ = 0;
    public boolean hasTaskType() { return hasTaskType; }
    public int getTaskType() { return taskType_; }
    
    // required int32 timeLimit = 17;
    public static final int TIMELIMIT_FIELD_NUMBER = 17;
    private boolean hasTimeLimit;
    private int timeLimit_ = 0;
    public boolean hasTimeLimit() { return hasTimeLimit; }
    public int getTimeLimit() { return timeLimit_; }
    
    // required int32 outputLimit = 18;
    public static final int OUTPUTLIMIT_FIELD_NUMBER = 18;
    private boolean hasOutputLimit;
    private int outputLimit_ = 0;
    public boolean hasOutputLimit() { return hasOutputLimit; }
    public int getOutputLimit() { return outputLimit_; }
    
    // required int32 testsCount = 19;
    public static final int TESTSCOUNT_FIELD_NUMBER = 19;
    private boolean hasTestsCount;
    private int testsCount_ = 0;
    public boolean hasTestsCount() { return hasTestsCount; }
    public int getTestsCount() { return testsCount_; }
    
    // required int32 memoryLimit = 20;
    public static final int MEMORYLIMIT_FIELD_NUMBER = 20;
    private boolean hasMemoryLimit;
    private int memoryLimit_ = 0;
    public boolean hasMemoryLimit() { return hasMemoryLimit; }
    public int getMemoryLimit() { return memoryLimit_; }
    
    @Override
    public final boolean isInitialized() {
      if (!hasTaskName) return false;
      if (!hasLanguage) return false;
      if (!hasExplicitGrade) return false;
      if (!hasTaskType) return false;
      if (!hasTimeLimit) return false;
      if (!hasOutputLimit) return false;
      if (!hasTestsCount) return false;
      if (!hasMemoryLimit) return false;
      return true;
    }
    
    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasTaskName()) {
        output.writeString(1, getTaskName());
      }
      if (hasLanguage()) {
        output.writeString(2, getLanguage());
      }
      for (int element : getTestIndexesList()) {
        output.writeInt32(3, element);
      }
      for (java.lang.String element : getMaxPointsList()) {
        output.writeString(4, element);
      }
      if (hasExplicitGrade()) {
        output.writeBool(5, getExplicitGrade());
      }
      if (hasTaskType()) {
        output.writeInt32(16, getTaskType());
      }
      if (hasTimeLimit()) {
        output.writeInt32(17, getTimeLimit());
      }
      if (hasOutputLimit()) {
        output.writeInt32(18, getOutputLimit());
      }
      if (hasTestsCount()) {
        output.writeInt32(19, getTestsCount());
      }
      if (hasMemoryLimit()) {
        output.writeInt32(20, getMemoryLimit());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasTaskName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getTaskName());
      }
      if (hasLanguage()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getLanguage());
      }
      {
        int dataSize = 0;
        for (int element : getTestIndexesList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getTestIndexesList().size();
      }
      {
        int dataSize = 0;
        for (java.lang.String element : getMaxPointsList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getMaxPointsList().size();
      }
      if (hasExplicitGrade()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, getExplicitGrade());
      }
      if (hasTaskType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(16, getTaskType());
      }
      if (hasTimeLimit()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(17, getTimeLimit());
      }
      if (hasOutputLimit()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(18, getOutputLimit());
      }
      if (hasTestsCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(19, getTestsCount());
      }
      if (hasMemoryLimit()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(20, getMemoryLimit());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static bg.smoc.model.GradeProto.Grade parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static bg.smoc.model.GradeProto.Grade parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static bg.smoc.model.GradeProto.Grade parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static bg.smoc.model.GradeProto.Grade parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static bg.smoc.model.GradeProto.Grade parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static bg.smoc.model.GradeProto.Grade parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static bg.smoc.model.GradeProto.Grade parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static bg.smoc.model.GradeProto.Grade parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static bg.smoc.model.GradeProto.Grade parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static bg.smoc.model.GradeProto.Grade parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(bg.smoc.model.GradeProto.Grade prototype) {
      return new Builder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using bg.smoc.model.GradeProto.Grade.newBuilder()
      private Builder() {}
      
      bg.smoc.model.GradeProto.Grade result = new bg.smoc.model.GradeProto.Grade();
      
      @Override
      protected bg.smoc.model.GradeProto.Grade internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new bg.smoc.model.GradeProto.Grade();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bg.smoc.model.GradeProto.Grade.getDescriptor();
      }
      
      public bg.smoc.model.GradeProto.Grade getDefaultInstanceForType() {
        return bg.smoc.model.GradeProto.Grade.getDefaultInstance();
      }
      
      public bg.smoc.model.GradeProto.Grade build() {
        if (result != null && !isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private bg.smoc.model.GradeProto.Grade buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public bg.smoc.model.GradeProto.Grade buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");  }
        if (result.testIndexes_ != java.util.Collections.EMPTY_LIST) {
          result.testIndexes_ =
            java.util.Collections.unmodifiableList(result.testIndexes_);
        }
        if (result.maxPoints_ != java.util.Collections.EMPTY_LIST) {
          result.maxPoints_ =
            java.util.Collections.unmodifiableList(result.maxPoints_);
        }
        bg.smoc.model.GradeProto.Grade returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof bg.smoc.model.GradeProto.Grade) {
          return mergeFrom((bg.smoc.model.GradeProto.Grade)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(bg.smoc.model.GradeProto.Grade other) {
        if (other == bg.smoc.model.GradeProto.Grade.getDefaultInstance()) return this;
        if (other.hasTaskName()) {
          setTaskName(other.getTaskName());
        }
        if (other.hasLanguage()) {
          setLanguage(other.getLanguage());
        }
        if (!other.testIndexes_.isEmpty()) {
          if (result.testIndexes_.isEmpty()) {
            result.testIndexes_ = new java.util.ArrayList<java.lang.Integer>();
          }
          result.testIndexes_.addAll(other.testIndexes_);
        }
        if (!other.maxPoints_.isEmpty()) {
          if (result.maxPoints_.isEmpty()) {
            result.maxPoints_ = new java.util.ArrayList<java.lang.String>();
          }
          result.maxPoints_.addAll(other.maxPoints_);
        }
        if (other.hasExplicitGrade()) {
          setExplicitGrade(other.getExplicitGrade());
        }
        if (other.hasTaskType()) {
          setTaskType(other.getTaskType());
        }
        if (other.hasTimeLimit()) {
          setTimeLimit(other.getTimeLimit());
        }
        if (other.hasOutputLimit()) {
          setOutputLimit(other.getOutputLimit());
        }
        if (other.hasTestsCount()) {
          setTestsCount(other.getTestsCount());
        }
        if (other.hasMemoryLimit()) {
          setMemoryLimit(other.getMemoryLimit());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return mergeFrom(input,
          com.google.protobuf.ExtensionRegistry.getEmptyRegistry());
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setTaskName(input.readString());
              break;
            }
            case 18: {
              setLanguage(input.readString());
              break;
            }
            case 24: {
              addTestIndexes(input.readInt32());
              break;
            }
            case 34: {
              addMaxPoints(input.readString());
              break;
            }
            case 40: {
              setExplicitGrade(input.readBool());
              break;
            }
            case 128: {
              setTaskType(input.readInt32());
              break;
            }
            case 136: {
              setTimeLimit(input.readInt32());
              break;
            }
            case 144: {
              setOutputLimit(input.readInt32());
              break;
            }
            case 152: {
              setTestsCount(input.readInt32());
              break;
            }
            case 160: {
              setMemoryLimit(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required string taskName = 1;
      public boolean hasTaskName() {
        return result.hasTaskName();
      }
      public java.lang.String getTaskName() {
        return result.getTaskName();
      }
      public Builder setTaskName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTaskName = true;
        result.taskName_ = value;
        return this;
      }
      public Builder clearTaskName() {
        result.hasTaskName = false;
        result.taskName_ = "";
        return this;
      }
      
      // required string language = 2;
      public boolean hasLanguage() {
        return result.hasLanguage();
      }
      public java.lang.String getLanguage() {
        return result.getLanguage();
      }
      public Builder setLanguage(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLanguage = true;
        result.language_ = value;
        return this;
      }
      public Builder clearLanguage() {
        result.hasLanguage = false;
        result.language_ = "";
        return this;
      }
      
      // repeated int32 testIndexes = 3;
      public java.util.List<java.lang.Integer> getTestIndexesList() {
        return java.util.Collections.unmodifiableList(result.testIndexes_);
      }
      public int getTestIndexesCount() {
        return result.getTestIndexesCount();
      }
      public int getTestIndexes(int index) {
        return result.getTestIndexes(index);
      }
      public Builder setTestIndexes(int index, int value) {
        result.testIndexes_.set(index, value);
        return this;
      }
      public Builder addTestIndexes(int value) {
        if (result.testIndexes_.isEmpty()) {
          result.testIndexes_ = new java.util.ArrayList<java.lang.Integer>();
        }
        result.testIndexes_.add(value);
        return this;
      }
      public Builder addAllTestIndexes(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        if (result.testIndexes_.isEmpty()) {
          result.testIndexes_ = new java.util.ArrayList<java.lang.Integer>();
        }
        super.addAll(values, result.testIndexes_);
        return this;
      }
      public Builder clearTestIndexes() {
        result.testIndexes_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated string maxPoints = 4;
      public java.util.List<java.lang.String> getMaxPointsList() {
        return java.util.Collections.unmodifiableList(result.maxPoints_);
      }
      public int getMaxPointsCount() {
        return result.getMaxPointsCount();
      }
      public java.lang.String getMaxPoints(int index) {
        return result.getMaxPoints(index);
      }
      public Builder setMaxPoints(int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.maxPoints_.set(index, value);
        return this;
      }
      public Builder addMaxPoints(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.maxPoints_.isEmpty()) {
          result.maxPoints_ = new java.util.ArrayList<java.lang.String>();
        }
        result.maxPoints_.add(value);
        return this;
      }
      public Builder addAllMaxPoints(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.maxPoints_.isEmpty()) {
          result.maxPoints_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.maxPoints_);
        return this;
      }
      public Builder clearMaxPoints() {
        result.maxPoints_ = java.util.Collections.emptyList();
        return this;
      }
      
      // required bool explicitGrade = 5;
      public boolean hasExplicitGrade() {
        return result.hasExplicitGrade();
      }
      public boolean getExplicitGrade() {
        return result.getExplicitGrade();
      }
      public Builder setExplicitGrade(boolean value) {
        result.hasExplicitGrade = true;
        result.explicitGrade_ = value;
        return this;
      }
      public Builder clearExplicitGrade() {
        result.hasExplicitGrade = false;
        result.explicitGrade_ = false;
        return this;
      }
      
      // required int32 taskType = 16;
      public boolean hasTaskType() {
        return result.hasTaskType();
      }
      public int getTaskType() {
        return result.getTaskType();
      }
      public Builder setTaskType(int value) {
        result.hasTaskType = true;
        result.taskType_ = value;
        return this;
      }
      public Builder clearTaskType() {
        result.hasTaskType = false;
        result.taskType_ = 0;
        return this;
      }
      
      // required int32 timeLimit = 17;
      public boolean hasTimeLimit() {
        return result.hasTimeLimit();
      }
      public int getTimeLimit() {
        return result.getTimeLimit();
      }
      public Builder setTimeLimit(int value) {
        result.hasTimeLimit = true;
        result.timeLimit_ = value;
        return this;
      }
      public Builder clearTimeLimit() {
        result.hasTimeLimit = false;
        result.timeLimit_ = 0;
        return this;
      }
      
      // required int32 outputLimit = 18;
      public boolean hasOutputLimit() {
        return result.hasOutputLimit();
      }
      public int getOutputLimit() {
        return result.getOutputLimit();
      }
      public Builder setOutputLimit(int value) {
        result.hasOutputLimit = true;
        result.outputLimit_ = value;
        return this;
      }
      public Builder clearOutputLimit() {
        result.hasOutputLimit = false;
        result.outputLimit_ = 0;
        return this;
      }
      
      // required int32 testsCount = 19;
      public boolean hasTestsCount() {
        return result.hasTestsCount();
      }
      public int getTestsCount() {
        return result.getTestsCount();
      }
      public Builder setTestsCount(int value) {
        result.hasTestsCount = true;
        result.testsCount_ = value;
        return this;
      }
      public Builder clearTestsCount() {
        result.hasTestsCount = false;
        result.testsCount_ = 0;
        return this;
      }
      
      // required int32 memoryLimit = 20;
      public boolean hasMemoryLimit() {
        return result.hasMemoryLimit();
      }
      public int getMemoryLimit() {
        return result.getMemoryLimit();
      }
      public Builder setMemoryLimit(int value) {
        result.hasMemoryLimit = true;
        result.memoryLimit_ = value;
        return this;
      }
      public Builder clearMemoryLimit() {
        result.hasMemoryLimit = false;
        result.memoryLimit_ = 0;
        return this;
      }
    }
    
    static {
      bg.smoc.model.GradeProto.getDescriptor();
    }
  }
  
  public static final class GradeResult extends
      com.google.protobuf.GeneratedMessage {
    // Use GradeResult.newBuilder() to construct.
    private GradeResult() {}
    
    private static final GradeResult defaultInstance = new GradeResult();
    public static GradeResult getDefaultInstance() {
      return defaultInstance;
    }
    
    public GradeResult getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bg.smoc.model.GradeProto.internal_static_model_GradeResult_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bg.smoc.model.GradeProto.internal_static_model_GradeResult_fieldAccessorTable;
    }
    
    // optional string sampleOutput = 1;
    public static final int SAMPLEOUTPUT_FIELD_NUMBER = 1;
    private boolean hasSampleOutput;
    private java.lang.String sampleOutput_ = "";
    public boolean hasSampleOutput() { return hasSampleOutput; }
    public java.lang.String getSampleOutput() { return sampleOutput_; }
    
    // repeated int32 testIndexes = 2;
    public static final int TESTINDEXES_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> testIndexes_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Integer> getTestIndexesList() {
      return testIndexes_;
    }
    public int getTestIndexesCount() { return testIndexes_.size(); }
    public int getTestIndexes(int index) {
      return testIndexes_.get(index);
    }
    
    // repeated string result = 3;
    public static final int RESULT_FIELD_NUMBER = 3;
    private java.util.List<java.lang.String> result_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getResultList() {
      return result_;
    }
    public int getResultCount() { return result_.size(); }
    public java.lang.String getResult(int index) {
      return result_.get(index);
    }
    
    // optional bool accept = 4;
    public static final int ACCEPT_FIELD_NUMBER = 4;
    private boolean hasAccept;
    private boolean accept_ = false;
    public boolean hasAccept() { return hasAccept; }
    public boolean getAccept() { return accept_; }
    
    @Override
    public final boolean isInitialized() {
      return true;
    }
    
    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasSampleOutput()) {
        output.writeString(1, getSampleOutput());
      }
      for (int element : getTestIndexesList()) {
        output.writeInt32(2, element);
      }
      for (java.lang.String element : getResultList()) {
        output.writeString(3, element);
      }
      if (hasAccept()) {
        output.writeBool(4, getAccept());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasSampleOutput()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getSampleOutput());
      }
      {
        int dataSize = 0;
        for (int element : getTestIndexesList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getTestIndexesList().size();
      }
      {
        int dataSize = 0;
        for (java.lang.String element : getResultList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getResultList().size();
      }
      if (hasAccept()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, getAccept());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static bg.smoc.model.GradeProto.GradeResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static bg.smoc.model.GradeProto.GradeResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static bg.smoc.model.GradeProto.GradeResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static bg.smoc.model.GradeProto.GradeResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static bg.smoc.model.GradeProto.GradeResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static bg.smoc.model.GradeProto.GradeResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static bg.smoc.model.GradeProto.GradeResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static bg.smoc.model.GradeProto.GradeResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static bg.smoc.model.GradeProto.GradeResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static bg.smoc.model.GradeProto.GradeResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(bg.smoc.model.GradeProto.GradeResult prototype) {
      return new Builder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using bg.smoc.model.GradeProto.GradeResult.newBuilder()
      private Builder() {}
      
      bg.smoc.model.GradeProto.GradeResult result = new bg.smoc.model.GradeProto.GradeResult();
      
      @Override
      protected bg.smoc.model.GradeProto.GradeResult internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new bg.smoc.model.GradeProto.GradeResult();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bg.smoc.model.GradeProto.GradeResult.getDescriptor();
      }
      
      public bg.smoc.model.GradeProto.GradeResult getDefaultInstanceForType() {
        return bg.smoc.model.GradeProto.GradeResult.getDefaultInstance();
      }
      
      public bg.smoc.model.GradeProto.GradeResult build() {
        if (result != null && !isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private bg.smoc.model.GradeProto.GradeResult buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public bg.smoc.model.GradeProto.GradeResult buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");  }
        if (result.testIndexes_ != java.util.Collections.EMPTY_LIST) {
          result.testIndexes_ =
            java.util.Collections.unmodifiableList(result.testIndexes_);
        }
        if (result.result_ != java.util.Collections.EMPTY_LIST) {
          result.result_ =
            java.util.Collections.unmodifiableList(result.result_);
        }
        bg.smoc.model.GradeProto.GradeResult returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof bg.smoc.model.GradeProto.GradeResult) {
          return mergeFrom((bg.smoc.model.GradeProto.GradeResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(bg.smoc.model.GradeProto.GradeResult other) {
        if (other == bg.smoc.model.GradeProto.GradeResult.getDefaultInstance()) return this;
        if (other.hasSampleOutput()) {
          setSampleOutput(other.getSampleOutput());
        }
        if (!other.testIndexes_.isEmpty()) {
          if (result.testIndexes_.isEmpty()) {
            result.testIndexes_ = new java.util.ArrayList<java.lang.Integer>();
          }
          result.testIndexes_.addAll(other.testIndexes_);
        }
        if (!other.result_.isEmpty()) {
          if (result.result_.isEmpty()) {
            result.result_ = new java.util.ArrayList<java.lang.String>();
          }
          result.result_.addAll(other.result_);
        }
        if (other.hasAccept()) {
          setAccept(other.getAccept());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return mergeFrom(input,
          com.google.protobuf.ExtensionRegistry.getEmptyRegistry());
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setSampleOutput(input.readString());
              break;
            }
            case 16: {
              addTestIndexes(input.readInt32());
              break;
            }
            case 26: {
              addResult(input.readString());
              break;
            }
            case 32: {
              setAccept(input.readBool());
              break;
            }
          }
        }
      }
      
      
      // optional string sampleOutput = 1;
      public boolean hasSampleOutput() {
        return result.hasSampleOutput();
      }
      public java.lang.String getSampleOutput() {
        return result.getSampleOutput();
      }
      public Builder setSampleOutput(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasSampleOutput = true;
        result.sampleOutput_ = value;
        return this;
      }
      public Builder clearSampleOutput() {
        result.hasSampleOutput = false;
        result.sampleOutput_ = "";
        return this;
      }
      
      // repeated int32 testIndexes = 2;
      public java.util.List<java.lang.Integer> getTestIndexesList() {
        return java.util.Collections.unmodifiableList(result.testIndexes_);
      }
      public int getTestIndexesCount() {
        return result.getTestIndexesCount();
      }
      public int getTestIndexes(int index) {
        return result.getTestIndexes(index);
      }
      public Builder setTestIndexes(int index, int value) {
        result.testIndexes_.set(index, value);
        return this;
      }
      public Builder addTestIndexes(int value) {
        if (result.testIndexes_.isEmpty()) {
          result.testIndexes_ = new java.util.ArrayList<java.lang.Integer>();
        }
        result.testIndexes_.add(value);
        return this;
      }
      public Builder addAllTestIndexes(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        if (result.testIndexes_.isEmpty()) {
          result.testIndexes_ = new java.util.ArrayList<java.lang.Integer>();
        }
        super.addAll(values, result.testIndexes_);
        return this;
      }
      public Builder clearTestIndexes() {
        result.testIndexes_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated string result = 3;
      public java.util.List<java.lang.String> getResultList() {
        return java.util.Collections.unmodifiableList(result.result_);
      }
      public int getResultCount() {
        return result.getResultCount();
      }
      public java.lang.String getResult(int index) {
        return result.getResult(index);
      }
      public Builder setResult(int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.result_.set(index, value);
        return this;
      }
      public Builder addResult(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.result_.isEmpty()) {
          result.result_ = new java.util.ArrayList<java.lang.String>();
        }
        result.result_.add(value);
        return this;
      }
      public Builder addAllResult(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.result_.isEmpty()) {
          result.result_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.result_);
        return this;
      }
      public Builder clearResult() {
        result.result_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional bool accept = 4;
      public boolean hasAccept() {
        return result.hasAccept();
      }
      public boolean getAccept() {
        return result.getAccept();
      }
      public Builder setAccept(boolean value) {
        result.hasAccept = true;
        result.accept_ = value;
        return this;
      }
      public Builder clearAccept() {
        result.hasAccept = false;
        result.accept_ = false;
        return this;
      }
    }
    
    static {
      bg.smoc.model.GradeProto.getDescriptor();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_model_Grade_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_model_Grade_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_model_GradeResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_model_GradeResult_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData =
      "\n\031bg/smoc/model/grade.proto\022\005model\"\315\001\n\005G" +
      "rade\022\020\n\010taskName\030\001 \002(\t\022\020\n\010language\030\002 \002(\t" +
      "\022\023\n\013testIndexes\030\003 \003(\005\022\021\n\tmaxPoints\030\004 \003(\t" +
      "\022\025\n\rexplicitGrade\030\005 \002(\010\022\020\n\010taskType\030\020 \002(" +
      "\005\022\021\n\ttimeLimit\030\021 \002(\005\022\023\n\013outputLimit\030\022 \002(" +
      "\005\022\022\n\ntestsCount\030\023 \002(\005\022\023\n\013memoryLimit\030\024 \002" +
      "(\005\"X\n\013GradeResult\022\024\n\014sampleOutput\030\001 \001(\t\022" +
      "\023\n\013testIndexes\030\002 \003(\005\022\016\n\006result\030\003 \003(\t\022\016\n\006" +
      "accept\030\004 \001(\010B\033\n\rbg.smoc.modelB\nGradeProt" +
      "o";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_model_Grade_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_model_Grade_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_model_Grade_descriptor,
              new java.lang.String[] { "TaskName", "Language", "TestIndexes", "MaxPoints", "ExplicitGrade", "TaskType", "TimeLimit", "OutputLimit", "TestsCount", "MemoryLimit", },
              bg.smoc.model.GradeProto.Grade.class,
              bg.smoc.model.GradeProto.Grade.Builder.class);
          internal_static_model_GradeResult_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_model_GradeResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_model_GradeResult_descriptor,
              new java.lang.String[] { "SampleOutput", "TestIndexes", "Result", "Accept", },
              bg.smoc.model.GradeProto.GradeResult.class,
              bg.smoc.model.GradeProto.GradeResult.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
}
